version: "3.9"

services:
  service:
    image: ecommerce-identity-service
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      logging/enabled: "true"
    container_name: ecommerce-identity-service
    ports:
      - 1000:8080
    env_file: .env
    environment:
      - GOOGLE_REDIRECT_URI=http://localhost:1000/api/v1/oauth/authorize/google/callback
      - USER_SERVICE_BASE_URI=http://host.docker.internal:1001
      - LOGIN_UI_BASE_URL=http://localhost:2000
      - JWT_SECRET=DockerTestJWTFakeSecret
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - ELASTIC_APM_SERVER_URL=http://host.docker.internal:8200
      - ELASTIC_APM_SERVICE_NAME=identity-service
      - ELASTIC_APM_EXIT_SPAN_MIN_DURATION=1us
      - ELASTIC_APM_CAPTURE_BODY=all
    restart: on-failure
