apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecommerce-identity-service
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: ecommerce-identity-service
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: jwt-secret
    - secretKey: client_id
      remoteRef:
        key: google-oauth-client-id
    - secretKey: client_secret
      remoteRef:
        key: google-oauth-client-secret
