apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-identity-service
spec:
  template:
    spec:
      containers:
        - name: ecommerce-identity-service
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-identity-service
                  key: jwt_secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ecommerce-identity-service
                  key: client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-identity-service
                  key: client_secret
            - name: GOOGLE_REDIRECT_URI
              value: https://identity.jameslucas.uk/api/v1/oauth/authorize/google/callback
            - name: ENVIRONMENT
              value: Production
            - name: LOGIN_UI_BASE_URL
              value: https://login.jameslucas.uk
            - name: USER_SERVICE_BASE_URI
              value: http://ecommerce-user-service.default.svc:80
